initial_joint_positions:
  joint_map:
    $(arg arm_id)_joint1 : 0
    $(arg arm_id)_joint2 : -0.785398163
    $(arg arm_id)_joint3 : 0
    $(arg arm_id)_joint4 : -2.35619449
    $(arg arm_id)_joint5 : 0
    $(arg arm_id)_joint6: 1.57079632679
    $(arg arm_id)_joint7 : 0.785398163397
    $(arg arm_id)_finger_joint1 : 0.001
    $(arg arm_id)_finger_joint2 : 0.001
