initial_joint_positions:
  joint_map: { panda_joint1 : 0, panda_joint2 : 0, panda_joint3 : 0, panda_joint4 : -1.57079632679, panda_joint5 : 0, panda_joint6: 1.57079632679, panda_joint7 : 0.785398163397, panda_finger_joint1 : 0.001, panda_finger_joint2 : 0.001}
